// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:9f10037e-500e-480b-bb84-1eb4c4dafd77",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BFMaBVd3r",
    "aws_user_pools_web_client_id": "41q8m3p3u9dgadcntufbbapt7u",
    "oauth": {}
};


export default awsmobile;
